# Generated by Django 4.2.7 on 2023-11-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('text', models.TextField()),
            ],
        ),
    ]
